<a href="https://colab.research.google.com/github/KushagraPan/machine-learning-zoomcamp/blob/main/Homework1_zoomcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:

print(pd.__version__)

url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

df = pd.read_csv(url)
df.head()

2.2.3

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [4]:
df.shape

(10000, 11)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB

In [6]:
print(df['horsepower'].isna().sum())
print(df['acceleration'].isna().sum())

877
264

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
df["origin"].value_counts()

origin
USA       4202
Asia      2994
Europe    2804
Name: count, dtype: int64

In [9]:
df['drivetrain'].value_counts()

drivetrain
Front-wheel drive    5519
Rear-wheel drive     2455
All-wheel drive      2026
Name: count, dtype: int64

In [10]:
df['fuel_type'].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

In [11]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [28]:
df.loc[df["origin"] == "Asia", "fuel_efficiency_mpg"].max()

41.2

In [13]:
df["horsepower"].value_counts()

horsepower
252.0    174
256.0    168
246.0    168
259.0    165
253.0    165
        ...
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 153, dtype: int64

In [14]:
mode = df["horsepower"].mode()[0]
mode

np.float64(252.0)

In [15]:
df['horsepower'].median()

254.0

In [16]:
df['horsepower'] = df['horsepower'].fillna(mode)

In [17]:
df['horsepower'].isna().sum()

np.int64(0)

In [18]:
df['horsepower'].median()

252.0

In [19]:
df['vehicle_weight'].sum()

np.int64(42867540)

In [20]:
vehicles_asia = df.loc[
    df["origin"] == "Asia",
    ["vehicle_weight", "model_year"]
].head(7)

X = vehicles_asia.to_numpy()

print(X)
print(X.shape)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
(7, 2)

In [21]:
Xt =X.T
print(Xt)

[[4240 4310 4230 4420 3950 4750 4450]
 [1996 1992 1997 1978 2007 2021 2019]]

In [22]:
XTX = Xt@X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [23]:
#Invert XTX
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [24]:
y= np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [25]:
type(y)

numpy.ndarray

In [26]:
w = XTX_inv@Xt@y
w

array([0.13644777, 0.2327492 ])

In [27]:
w.sum()

np.float64(0.36919696904925486)